const schema = `
PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS project (id TEXT PRIMARY KEY, name TEXT NOT NULL, metadata_json TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
INSERT OR IGNORE INTO project(id, name, created_at, updated_at) VALUES ('default', 'Default project', datetime('now'), datetime('now'));
CREATE TABLE IF NOT EXISTS agent (id TEXT PRIMARY KEY, project_id TEXT NOT NULL DEFAULT 'default', name TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'worker', status TEXT NOT NULL DEFAULT 'offline', last_seen_at TEXT, metadata_json TEXT NOT NULL DEFAULT '{}', token_hash TEXT, token_issued_at TEXT, token_revoked_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS task_item (id TEXT PRIMARY KEY, board_id TEXT NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', phase TEXT NOT NULL DEFAULT 'pending' CHECK (phase IN ('pending', 'ready', 'in_progress', 'done')), priority INTEGER NOT NULL DEFAULT 5, assignee_agent_id TEXT, sort_order INTEGER NOT NULL DEFAULT 0, lease_owner TEXT, lease_expires_at TEXT, lease_generation INTEGER NOT NULL DEFAULT 0, attempt_count INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT, review_status TEXT CHECK (review_status IN ('pass', 'reject')), review_agent_id TEXT, review_note TEXT, reviewed_at TEXT, verify_status TEXT CHECK (verify_status IN ('pass', 'reject')), verify_agent_id TEXT, verify_note TEXT, verified_at TEXT, FOREIGN KEY (assignee_agent_id) REFERENCES agent(id));
CREATE TABLE IF NOT EXISTS task_dependency (task_id TEXT NOT NULL, depends_on_id TEXT NOT NULL, PRIMARY KEY (task_id, depends_on_id), CHECK (task_id <> depends_on_id), FOREIGN KEY (task_id) REFERENCES task_item(id) ON DELETE CASCADE, FOREIGN KEY (depends_on_id) REFERENCES task_item(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS agent_session (id TEXT PRIMARY KEY, agent_id TEXT NOT NULL, started_at TEXT NOT NULL, last_heartbeat_at TEXT NOT NULL, disconnected_at TEXT, metadata_json TEXT NOT NULL DEFAULT '{}', FOREIGN KEY (agent_id) REFERENCES agent(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS task_event (id TEXT PRIMARY KEY, task_id TEXT NOT NULL, actor_agent_id TEXT, event_type TEXT NOT NULL, payload_json TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL, FOREIGN KEY (task_id) REFERENCES task_item(id) ON DELETE CASCADE, FOREIGN KEY (actor_agent_id) REFERENCES agent(id));
CREATE TABLE IF NOT EXISTS idempotency_key (scope TEXT NOT NULL, key TEXT NOT NULL, response_status INTEGER, response_body TEXT, created_at TEXT NOT NULL, PRIMARY KEY (scope, key));
CREATE TABLE IF NOT EXISTS message (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, sender_agent_id TEXT, kind TEXT NOT NULL CHECK (kind IN ('direct', 'broadcast')), subject TEXT, payload_json TEXT NOT NULL DEFAULT '', reply_to TEXT, created_at TEXT NOT NULL, FOREIGN KEY (sender_agent_id) REFERENCES agent(id), FOREIGN KEY (reply_to) REFERENCES message(id));
CREATE TABLE IF NOT EXISTS message_delivery (id TEXT PRIMARY KEY, message_id TEXT NOT NULL, project_id TEXT NOT NULL, recipient_agent_id TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'unread' CHECK (status IN ('unread', 'seen', 'acked', 'nacked', 'dead')), seen_at TEXT, acked_at TEXT, attempt_count INTEGER NOT NULL DEFAULT 0, updated_at TEXT NOT NULL, UNIQUE (message_id, recipient_agent_id), FOREIGN KEY (message_id) REFERENCES message(id) ON DELETE CASCADE, FOREIGN KEY (recipient_agent_id) REFERENCES agent(id));
`;
export default schema;
